## **BT thực hành 2.1.6: Cholesky Decomposition 2**


> Cập nhật: **07/2023**



In [2]:
## Thư viện
import numpy    as np
import warnings
warnings.filterwarnings('ignore')

In [3]:
## Tạo ma trận VUÔNG A(3, 3) với các giá trị ngẫu nhiên từ 3 đến 9
m, n, min, max = 3, 3, 3, 9
A = np.random.randint(min, max, (m, n))

A

array([[7, 4, 8],
       [7, 7, 8],
       [5, 7, 6]])

In [4]:
## Chuyển A thành ma trận vuông đối xứng (theo tam giác dưới)
## Điều kiện phân rã Cholesky: ma trận ĐỐI XỨNG
for i in range(A.shape[0]):
    for j in range(i):
        A[j][i] = A[i][j]
print('*** Ma trận A', A.shape, ':\n', A)

*** Ma trận A (3, 3) :
 [[7 7 5]
 [7 7 7]
 [5 7 6]]


In [5]:
## Thực hiện phân rã Cholesky, nếu có thể
##    Hàm eigvalsh() chỉ trả về eigenvalues (khôngtạo eigenvectors)
##    Kiểm tra ma trận xác định dương (tất cả trị riêng > 0)
eigenvalues = np.linalg.eigvalsh(A)

pos_def = np.all(eigenvalues > 0)
if (pos_def == True):
    L = cholesky(A)

    print('Ma trận L', L.shape, ':\n', L)

    print('Tái tạo ma trận A:\n', L.dot(L.T))
else:
    print('\nMa trận A KHÔNG thỏa điều kiện XÁC ĐỊNH DƯƠNG')


Ma trận A KHÔNG thỏa điều kiện XÁC ĐỊNH DƯƠNG


In [6]:
##------------------------------------------------------------------------------
## Hàm tạo ma trận xác định dương
##------------------------------------------------------------------------------
def create_matrix_positive_definite(m, n, start, end):
    A       = None
    pos_def = False

    while (pos_def == False):
        A = np.random.randint(start, end, (m, n))
        for i in range(A.shape[0]):
            for j in range(i):
                A[j][i] = A[i][j]
        test    = np.linalg.eigvalsh(A)
        pos_def = np.all(test > 0)
    return A
##------------------------------------------------------------------------------

In [7]:
## Tạo ma trận xác định dương A
A = create_matrix_positive_definite(3, 3, 0, 10)
print('\n*** Ma trận A', A.shape, 'thỏa điều kiện XÁC ĐỊNH DƯƠNG:\n', A)

from numpy.linalg import cholesky
## numpy.linalg.cholesky: Default --> LOWER

print('Áp dụng phân rã Cholesky:')
L = cholesky(A)
print('Ma trận L', L.shape, ':\n', L)

print('\nTái tạo A từ L, L_T (kiểm chứng lại phép phân rã)\n', L @ L.T)


*** Ma trận A (3, 3) thỏa điều kiện XÁC ĐỊNH DƯƠNG:
 [[6 4 4]
 [4 3 2]
 [4 2 8]]
Áp dụng phân rã Cholesky:
Ma trận L (3, 3) :
 [[ 2.44948974  0.          0.        ]
 [ 1.63299316  0.57735027  0.        ]
 [ 1.63299316 -1.15470054  2.        ]]

Tái tạo A từ L, L_T (kiểm chứng lại phép phân rã)
 [[6. 4. 4.]
 [4. 3. 2.]
 [4. 2. 8.]]
