## **BT thực hành 2.1.4: QR Decomposition**
- Tạo ma trận A(4x5) chứa các giá trị ngẫu nhiên trong khoảng 5 - 10
- Phân tích thành các thành phần Q, R. In kết quả
- Tái tạo ma trận A từ các thành phần Q, R.


> Cập nhật: **07/2023**



In [1]:
## Thư viện
import numpy    as np
import warnings
warnings.filterwarnings('ignore')

from   numpy.linalg import qr

In [4]:
## Tạo ma trận A(4, 5) với các giá trị ngẫu nhiên từ 1 đến 10
m, n, min, max = 4, 5, 1, 10
A = np.random.randint(min, max + 1, (m, n))

A

array([[10,  3,  5, 10,  3],
       [ 9,  9,  9,  5,  2],
       [ 7,  2,  8,  8,  3],
       [ 1,  6,  1,  5,  5]])

In [5]:
## Phân rã Q, R
## Các giá trị tham số
##     'complete' : returns Q, R with dimensions (…, m, m), (…, m, n)
##     'reduced'  : returns Q, R with dimensions (…, m, k), (…, k, n) (default)
Q, R = qr(A)

In [6]:
## Ma trận vuông trực chuẩn Q
Q

array([[-0.65795169,  0.35785474,  0.65497866,  0.10021228],
       [-0.59215653, -0.52199233, -0.22208223, -0.57232346],
       [-0.46056619,  0.26389612, -0.68350209,  0.50106139],
       [-0.06579517, -0.7278893 ,  0.23346804,  0.64135859]])

In [7]:
## Kiểm chứng tính trực giao của Q
print(np.rint(Q @ Q.T).astype(int)) # rint(): làm tròn số

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [8]:
## Ma trận tam giác trên R
R

array([[-15.19868415,  -8.6191672 , -12.36949187, -13.55380492,
         -4.86884254],
       [  0.        ,  -7.46391028,  -1.52537758,  -0.55969177,
         -2.81817857],
       [  0.        ,   0.        ,  -3.95839541,   1.13869901,
          0.63760549],
       [  0.        ,   0.        ,   0.        ,   5.35578958,
          3.86596703]])

In [12]:
## Tái tạo A từ các thành phần Q, R (kiểm chứng lại phép phân rã)
print(np.rint(Q @ R).astype(int))

[[10  3  5 10  3]
 [ 9  9  9  5  2]
 [ 7  2  8  8  3]
 [ 1  6  1  5  5]]
