## **BT thực hành 2.1.5: Cholesky Decomposition 1**


> Cập nhật: **07/2023**



In [1]:
## Thư viện
import numpy    as np
import warnings
warnings.filterwarnings('ignore')

from scipy.linalg import cholesky

In [2]:
## Positive definite (SYMETRIC) matrix
A = np.array([[6, 1, 1],
              [1, 6, 1],
              [1, 1, 6]])

In [3]:
## Cholesky decomposition: Default --> UPPER (U)
U = cholesky(A)
print('\nUPPER   Cholesky factor:\n', U)
print('\nTái tạo A từ U, U_T (kiểm chứng lại phép phân rã)\n', U.T @ U)

U = cholesky(A, lower = False)
print('\nUPPER   Cholesky factor:\n', U)

L = cholesky(A, lower = True)
print('\nLOWER   Cholesky factor:\n', L)
print('\nTái tạo A từ L, L_T (kiểm chứng lại phép phân rã)\n', L @ L.T)


UPPER   Cholesky factor:
 [[2.44948974 0.40824829 0.40824829]
 [0.         2.41522946 0.34503278]
 [0.         0.         2.39045722]]

Tái tạo A từ U, U_T (kiểm chứng lại phép phân rã)
 [[6. 1. 1.]
 [1. 6. 1.]
 [1. 1. 6.]]

UPPER   Cholesky factor:
 [[2.44948974 0.40824829 0.40824829]
 [0.         2.41522946 0.34503278]
 [0.         0.         2.39045722]]

LOWER   Cholesky factor:
 [[2.44948974 0.         0.        ]
 [0.40824829 2.41522946 0.        ]
 [0.40824829 0.34503278 2.39045722]]

Tái tạo A từ L, L_T (kiểm chứng lại phép phân rã)
 [[6. 1. 1.]
 [1. 6. 1.]
 [1. 1. 6.]]


In [6]:
## Positive definite (NON-SYMETRIC) matrix
A = np.array([[  4,  12, -15],
              [ 12,  37, -42],
              [-16, -43,  98]])

# Cholesky decomposition
U = cholesky(A)
print('UPPER   Cholesky factor:\n', U)
print('\nTái tạo A từ U, U_T (kiểm chứng lại phép phân rã)\n', U.T @ U)

U = cholesky(A, lower = False)
print('UPPER   Cholesky factor:\n', U)

L = cholesky(A, lower = True)
print('LOWER   Cholesky factor:\n', L)
print('\nTái tạo A từ L, L_T (kiểm chứng lại phép phân rã)\n', L @ L.T)

UPPER   Cholesky factor:
 [[ 2.          6.         -7.5       ]
 [ 0.          1.          3.        ]
 [ 0.          0.          5.72276157]]

Tái tạo A từ U, U_T (kiểm chứng lại phép phân rã)
 [[  4.  12. -15.]
 [ 12.  37. -42.]
 [-15. -42.  98.]]
UPPER   Cholesky factor:
 [[ 2.          6.         -7.5       ]
 [ 0.          1.          3.        ]
 [ 0.          0.          5.72276157]]
LOWER   Cholesky factor:
 [[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  3.]]

Tái tạo A từ L, L_T (kiểm chứng lại phép phân rã)
 [[  4.  12. -16.]
 [ 12.  37. -43.]
 [-16. -43.  98.]]


In [7]:
##------------------------------------------------------------------------------
##   Kiểm tra tính chất POSITIVE DEFINITE của ma trận A
##------------------------------------------------------------------------------
# Positive DEFINITE (symmetric) matrix
A = np.array([[9, 6],
              [6, 5]])

from numpy import linalg   as la

# Eigenvalues
eigenValues, eigenVectors = la.eig(A)
pos_def = np.all(eigenValues > 0)
if (pos_def == True):
    print('\n*** Ma trận\n', A, '\nlà ma trận xác định dương.')
    print('Áp dụng phân rã Cholesky:')
    print('UPPER Cholesky factor:\n', cholesky(A))
    print('UPPER Cholesky factor:\n', cholesky(A, check_finite = True))
else:
    print('\n*** Ma trận\n', A, '\nKHÔNG phải là ma trận xác định dương.')

# Positive SEMIDEFINITE (symmetric) matrix
#    A positive semidefinite matrix is a Hermitian matrix all of whose eigenvalues
#    are nonnegative.
A = np.array([[9, 6], [6, 4]])

# Eigenvalues
eigenValues, eigenVectors = la.eig(A)
pos_def = np.all(eigenValues > 0)
if (pos_def == True):
    print('\n*** Ma trận\n', A, '\nlà ma trận xác định dương.')
    print('Áp dụng phân rã Cholesky:')
    print('UPPER Cholesky factor:\n', cholesky(A, check_finite = True))
else:
    print('\n*** Ma trận\n', A, '\nKHÔNG phải là ma trận xác định dương.')

# NOT Positive SEMIDEFINITE (symmetric) matrix
A = np.array([[9, 6], [6, 3]])

# Eigenvalues
eigenValues, eigenVectors = la.eig(A)
pos_def = np.all(eigenValues > 0)
if (pos_def == True):
    print('\n*** Ma trận\n', A, '\nlà ma trận xác định dương.')
    print('Áp dụng phân rã Cholesky:')
    print('UPPER Cholesky factor:\n', cholesky(A, check_finite = True))
else:
    print('\n*** Ma trận\n', A, '\nKHÔNG phải là ma trận xác định dương.')



*** Ma trận
 [[9 6]
 [6 5]] 
là ma trận xác định dương.
Áp dụng phân rã Cholesky:
UPPER Cholesky factor:
 [[3. 2.]
 [0. 1.]]
UPPER Cholesky factor:
 [[3. 2.]
 [0. 1.]]

*** Ma trận
 [[9 6]
 [6 4]] 
là ma trận xác định dương.
Áp dụng phân rã Cholesky:


LinAlgError: 2-th leading minor of the array is not positive definite