## **BT thực hành 2.2.1: Eigenvalues và eigenvectors**


> Cập nhật: **07/2023**



---
## **Yêu cầu 1:**
- Tạo ma trận A(4x4) với các giá trị ngẫu nhiên từ 1 đến 10
- Tìm eigenvalues (lambda[i]) và eigenvectors (v[i]) của A
- Kiểm chứng eigenvector đầu tiên: A.v[0] = lambda[0].v[0] ?
- Nếu bằng nhau thì tái tạo A từ các eigenvectors và eigenvalues
---

In [1]:
## Thư viện
import numpy    as np
import warnings
warnings.filterwarnings('ignore')

from numpy        import diag
from numpy.linalg import eig, inv

In [2]:
## Tạo ma trận A(4, 4) với các giá trị ngẫu nhiên từ 1 đến 10
m, n, min, max = 4, 4, 1, 10
A = np.random.randint(min, max + 1, (m, n))
A

array([[ 5,  5, 10,  3],
       [ 7,  1,  5,  3],
       [ 4,  8, 10,  3],
       [10,  5,  5,  5]])

In [3]:
## Tìm eigenvalues và eigenvectors của A
values, vectors = eig(A)

In [4]:
## Hiển thị kết quả: Trị riêng lambda(r: số thực, i: số phức)
for j in range(len(values)):
    eigenvalue = values[j]

    r = values[j].real
    i = values[j].imag
    print('Eigenvalue[%1d]' %j, '= (%f,' %r, '%f)' %i)

print('\nEigenvectors', vectors.shape, ':\n', vectors)

Eigenvalue[0] = (22.404727, 0.000000)
Eigenvalue[1] = (0.689000, 0.000000)
Eigenvalue[2] = (-1.046863, 1.348769)
Eigenvalue[3] = (-1.046863, -1.348769)

Eigenvectors (4, 4) :
 [[-0.51226231+0.j         -0.31766816+0.j          0.42031948-0.05298379j
   0.42031948+0.05298379j]
 [-0.37137274+0.j         -0.05937914+0.j          0.17847201-0.37064814j
   0.17847201+0.37064814j]
 [-0.5391252 +0.j         -0.11515618+0.j         -0.11097725+0.27405404j
  -0.11097725-0.27405404j]
 [-0.55588995+0.j          0.93930831+0.j         -0.75091303+0.j
  -0.75091303-0.j        ]]


In [5]:
## Kiểm chứng eigenvector đầu tiên: A.v[0] = lambda[0].v[0] ?
v0      = vectors[:, 0]
lambda0 = values[0]     # Chú ý phần số thực
print('A @ v[0]         =', A @ v0)
print('lambda[0] @ v[0] =', lambda0 * v0)

A @ v[0]         = [-11.4770971 +0.j  -8.32050475+0.j -12.078953  +0.j -12.45456251+0.j]
lambda[0] @ v[0] = [-11.4770971 +0.j  -8.32050475+0.j -12.078953  +0.j -12.45456251+0.j]


In [8]:
## Tái tạo A từ các eigenvectors và eigenvalues:A = Q @ Lambda @ Q_1
Q = vectors
Lambda = diag(values)

print('\nTái tạo ma trận A:\n', np.rint(Q @ Lambda @ inv(Q)).astype(int))
# Nhận xét: A có phải là ma trận chéo hóa được ?


Tái tạo ma trận A:
 [[ 5  5 10  3]
 [ 7  1  5  3]
 [ 4  8 10  3]
 [10  5  5  5]]


In [10]:
## Hàm eigvalsh() chỉ trả về eigenvalues (khôngtạo eigenvectors)
eigenvalues = np.linalg.eigvalsh(A)
print(eigenvalues)

[-6.43714873 -3.38972504  5.90226432 24.92460945]


---
## **Yêu cầu 2:**
- Thực hiện Yêu cầu 1 với ma trận:
       [ 9, 11,  1,  2]
       [ 7,  5, 10,  4]
       [ 2, 10,  1,  1]
       [ 1,  1, 10,  9]
---

In [11]:
A = np.array([[ 9, 11,  1,  2],
              [ 7,  5, 10,  4],
              [ 2, 10,  1,  1],
              [ 1,  1, 10,  9]])

## Tìm eigenvalues và eigenvectors của A
values, vectors = eig(A)
print('Eigenvalues :', values)
print('Eigenvectors:\n', vectors)

Eigenvalues : [21.34262129 -7.78284152  3.29387086  7.14634936]
Eigenvectors:
 [[-0.61158649 -0.38855303 -0.25905455 -0.37518308]
 [-0.58162527  0.58418387  0.23969712 -0.09183239]
 [-0.36534641 -0.61720767  0.46517086 -0.12275652]
 [-0.392678    0.35610453 -0.81182024  0.9141856 ]]


In [14]:
## Tái tạo A từ các eigenvectors và eigenvalues:A = Q @ Lambda @ Q_1
Q = vectors
Lambda = diag(values)
print('\nTái tạo ma trận A:\n', np.rint(Q @ Lambda @ inv(Q)).astype(int))


Tái tạo ma trận A:
 [[ 9 11  1  2]
 [ 7  5 10  4]
 [ 2 10  1  1]
 [ 1  1 10  9]]
