##**BT thực hành 2.2.2: Eigenvalues và eigenvectors của ma trận đối xứng**


> Cập nhật: **07/2023**



In [1]:
import numpy      as np
import warnings
warnings.filterwarnings('ignore')

from numpy.linalg import eig, inv
from numpy        import diag

In [2]:
## Tạo ma trận A(5 x 5) chứa các giá trị ngẫu nhiên trong khoảng 1 - 10
m, n, min, max = 5, 5, 1, 10
A = np.random.randint(min, max + 1, (m, n))
print('Ma trận A', A.shape, ':\n', A)

Ma trận A (5, 5) :
 [[ 4  3  5  6  2]
 [ 6  1  4  3 10]
 [ 4  4  2  6  7]
 [ 1  9 10  6  8]
 [ 7  8  2  9  5]]


In [3]:
## Tạo ma trận đối xứng  B = A @ A.T
B = A @ A.T
B

array([[ 90,  85,  88, 133, 126],
       [ 85, 162, 124, 153, 135],
       [ 88, 124, 121, 152, 153],
       [133, 153, 152, 282, 193],
       [126, 135, 153, 193, 223]])

In [4]:
## Tìm eigenvalues và eigenvectors của B
values, vectors = eig(B)

In [5]:
## Hiển thị kết quả: Trị riêng lambda(r: số thực, i: số phức)
for j in range(len(values)):
    eigenvalue = values[j]

    r = values[j].real
    i = values[j].imag
    print('Eigenvalue[%1d]' %j, '= (%f,' %r, '%f)' %i)

print('\nEigenvectors', vectors.shape, ':\n', vectors)

Eigenvalue[0] = (741.093766, 0.000000)
Eigenvalue[1] = (13.128717, 0.000000)
Eigenvalue[2] = (1.913533, 0.000000)
Eigenvalue[3] = (57.151172, 0.000000)
Eigenvalue[4] = (64.712812, 0.000000)

Eigenvectors (5, 5) :
 [[-0.32012874 -0.88244884  0.23239633 -0.24902937 -0.05270634]
 [-0.400098   -0.16283983 -0.30469068  0.70786155  0.46850869]
 [-0.39091012  0.3330305   0.81141485  0.02072173  0.2783101 ]
 [-0.56983209  0.17563583 -0.08598839  0.1937754  -0.7742742 ]
 [-0.50982334  0.23023897 -0.43285964 -0.63161547  0.31743442]]


---
### **Nhận xét:**
- Ma trận ĐỐI XỨNG có các giá trị riêng đều là SỐ THỰC !
---

In [6]:
## Tái tạo B từ các eigenvectors và eigenvalues: B = Q @ Lambda @ Q_1
from numpy.linalg import inv
Q = vectors
Lambda = diag(values)

print('Tái tạo ma trận B:\n', np.rint(Q @ Lambda @ inv(Q)).astype(int))

Tái tạo ma trận B:
 [[ 90  85  88 133 126]
 [ 85 162 124 153 135]
 [ 88 124 121 152 153]
 [133 153 152 282 193]
 [126 135 153 193 223]]
