## **BT thực hành 2.3.3: SVD**


> Cập nhật: **07/2023**



---
## **Yêu cầu: Phân tích iris.csv**
- Đọc tập tin **iris.csv** vào dataframe và chỉ lấy 4 cột đầu
- Phân tích SVD: U, S, VT từ dataframe
- Tạo dataframe mới từ các thành phần đã phân tích, nhưng có nhận xét và rút gọn thành phần nếu có thể.
- Tính sai số nếu có rút gọn thành phần
- Tái tạo dataframe theo U, S, VT (giữ nguyên tất cả các thành phần)
---

In [ ]:
## Môi trường lập trình
from google.colab import drive
drive.mount("/content/gdrive", force_remount = True)
folder = '/content/gdrive/My Drive/Edu/Chia se hoc lieu/LDS3/Bai tap HV/Ch2_Factorization'

Mounted at /content/gdrive


In [ ]:
## Thư viện
import numpy    as np
import pandas   as pd
import warnings
warnings.filterwarnings('ignore')

In [ ]:
## Mở tập tin dữ liệu iris.csv
iris = pd.read_csv(folder + '/Data/iris.csv')

## Xem dữ liệu
print(iris.shape)
print(iris.head())

(150, 5)
   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa


In [ ]:
## Chỉ sử dụng 4 cột đầu tiên (cột 'species' là nhãn phân loại - target)
X = iris[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]
X.head()

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [ ]:
## Phân tích SVD
U, s, VT = np.linalg.svd(X)

In [ ]:
## Hiển thị kết quả
print('* Ma trận U(', U.shape[1], ', ', U.shape[0], '): \n', U, '\n')
print('* Singular values:', s, '\n')
print('* Ma trận VT(', VT.shape[1], ', ', VT.shape[0], '): \n', VT, '\n')

* Ma trận U( 150 ,  150 ): 
 [[-6.16171172e-02  1.29969428e-01 -5.58364155e-05 ... -9.34637342e-02
  -9.60224157e-02 -8.09922905e-02]
 [-5.80722977e-02  1.11371452e-01  6.84386629e-02 ...  3.66755322e-02
  -3.24463474e-02  1.27273399e-02]
 [-5.67633852e-02  1.18294769e-01  2.31062793e-03 ...  3.08252776e-02
   1.95234663e-01  1.35567696e-01]
 ...
 [-9.40702260e-02 -4.98348018e-02 -4.14958083e-02 ...  9.81822841e-01
  -2.17978813e-02 -8.85972146e-03]
 [-9.48993908e-02 -5.62107520e-02 -2.12386574e-01 ... -2.14264126e-02
   9.42038920e-01 -2.96933496e-02]
 [-8.84882764e-02 -5.16210172e-02 -9.51442925e-02 ... -8.52768485e-03
  -3.02139863e-02  9.73577349e-01]] 

* Singular values: [95.95066751 17.72295328  3.46929666  1.87891236] 

* Ma trận VT( 4 ,  4 ): 
 [[-0.75116805 -0.37978837 -0.51315094 -0.16787934]
 [ 0.28583096  0.54488976 -0.70889874 -0.34475845]
 [ 0.49942378 -0.67502499 -0.05471983 -0.54029889]
 [ 0.32345496 -0.32124324 -0.48077482  0.74902286]] 



### **Nhận xét:**
Hai trị riêng đầu tiên có cường độ vượt trội so với các trị riêng còn lại. Điều đó có nghĩa là 2 vectors riêng đầu tiên đóng vai trò quan trọng hơn rất nhiều và chúng ta có thể tái tạo dữ liệu chỉ bằng hai hàng đầu tiên của V và hai cột đầu tiên của U.

In [ ]:
## Chỉ sử dụng 2 singular values và 2 eigen vectors đầu tiên
D = np.matrix(U[:, :2]) * np.diag(s[:2]) * np.matrix(VT[:2, :])
print('- Ma trận D(', D.shape[0], ',', D.shape[1], '): \n', D[0:5], '\n')

- Ma trận D( 150 , 4 ): 
 [[5.09945346 3.50050812 1.40094556 0.19840569]
 [4.74974728 3.19172985 1.46006954 0.25494146]
 [4.69047924 3.2108907  1.30863935 0.1915549 ]
 [4.61834831 3.08439659 1.46266616 0.26731753]
 [5.07896131 3.5005194  1.36352353 0.18323972]] 



In [ ]:
## Chuyển vào dataframe
Xnew = pd.DataFrame(D, index = X.index, columns = X.columns)
print(Xnew.head())

   sepal_length  sepal_width  petal_length  petal_width
0      5.099453     3.500508      1.400946     0.198406
1      4.749747     3.191730      1.460070     0.254941
2      4.690479     3.210891      1.308639     0.191555
3      4.618348     3.084397      1.462666     0.267318
4      5.078961     3.500519      1.363524     0.183240


In [ ]:
## Sai số so với dữ liệu ban đầu: (X - D)
print((X - D).head().to_string(index = False))

 sepal_length  sepal_width  petal_length  petal_width
     0.000547    -0.000508     -0.000946     0.001594
     0.150253    -0.191730     -0.060070    -0.054941
     0.009521    -0.010891     -0.008639     0.008445
    -0.018348     0.015603      0.037334    -0.067318
    -0.078961     0.099481      0.036476     0.016760


In [ ]:
## Tái tạo ma trận dữ liệu (giữ nguyên các thành phần)
Sigma = np.zeros((X.shape[0], X.shape[1]))
Sigma[:X.shape[1], :X.shape[1]] = np.diag(s)

X_c = U @ Sigma @ VT
X_c[0:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [ ]:
## Chuyển vào dataframe
X_c_new = pd.DataFrame(X_c, columns  =X.columns)
X_c_new.head()

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2