## **BT thực hành 2.3.5: Giảm chiều dữ liệu Digits**
- Tải dữ liệu digits từ dataset của sklearn
- Áp dụng TruncatedSVD để giảm chiều dữ liệu chỉ còn 10 components
- Xác định tỷ lệ % dữ liệu được giữ lại sau giảm chiều


> Cập nhật: **07/2023**



In [1]:
## Thư viện
import numpy    as np
import pandas   as pd
import warnings
warnings.filterwarnings('ignore')

from scipy.sparse          import csr_matrix
from sklearn               import datasets
from sklearn.decomposition import TruncatedSVD

In [2]:
## Tải dữ liệu Digits từ dataset của sklearn (1797 dòng và 64 cột)
digits = datasets.load_digits()
print(digits.data.shape)
print(digits.data)

(1797, 64)
[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]


In [3]:
## Xử lý ma trận thưa
X        = digits.data
X_sparse = csr_matrix(X)

In [5]:
## Khai báo số chiều muốn giảm: k = 10
tsvd = TruncatedSVD(n_components = 10)

In [6]:
## Thực hiện truncatedSVD (.fit())và chuyển tọa độ trong không gian mới (phép chiếu)
X_sparse_tsvd = tsvd.fit(X_sparse).transform(X_sparse)

In [7]:
## Hiển thị kết quả
print('Số chiều ban đầu =', X_sparse.shape[1])
print('Số chiều đã giảm =', X_sparse_tsvd.shape[1])

print('Số mẫu ban đầu   =', X_sparse.shape[0])
print('Số mẫu xử lý     =', X_sparse_tsvd.shape[0])

Số chiều ban đầu = 64
Số chiều đã giảm = 10
Số mẫu ban đầu   = 1797
Số mẫu xử lý     = 1797


In [8]:
## Dòng 0 của dữ liệu ban đầu
X[0]

array([ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
       15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
       12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
        0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
       10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.])

In [9]:
## Dòng 0 của dữ liệu đã giảm chiều
X_sparse_tsvd[0]

array([45.86127719, -1.19211573, 21.10005921, -9.48896862, 13.04312056,
       -7.01647569, -8.96023388,  0.39652778,  1.3099474 , -1.39201542])

In [10]:
## Tỷ lệ % dữ liệu còn giữ lại (explained variance)
tsvd.explained_variance_ratio_[0:10].sum()

0.7324265058890624