---
## **BT thực hành 2.3.1: Phương pháp SVD**
- Ma trận VUÔNG
- Ma trận HÌNH CHỮ NHẬT (m > n)
- Ma trận HÌNH CHỮ NHẬT (m < n)

> Cập nhật: **07/2023**


---

In [1]:
## Thư viện
import numpy      as np
import warnings
warnings.filterwarnings('ignore')

from numpy        import array
from scipy.linalg import svd

In [2]:
## Các ma trận thử nghiệm A[m, n]
ma_tran_vuong = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
ma_tran_hcn1  = array([[1, 2], [3, 4], [5, 6]])
ma_tran_hcn2  = array([[3, 1, 1], [-1, 3, 1]])

In [3]:
## Chọn 1 trong các ma trận thử nghiệm
A = ma_tran_hcn1
m = A.shape[0]  # rows
n = A.shape[1]  # cols
k = min(m, n)
print('Ma trận A(', A.shape, ':\n', A)

Ma trận A( (3, 2) :
 [[1 2]
 [3 4]
 [5 6]]


In [4]:
## Áp dụng SVD với các ma trận kết quả U[m, m], VT[n, n]
U, sglrValues, VT = svd(A)

In [6]:
## Ma trận U[m, m] (left-eigen vectors)
print('Ma trận U' , U.shape, ':\n', U)

## Ma trận S[m, n] chứa các real-non negative singular values
S = np.zeros(A.shape)
S[:k, :k] = np.diag(sglrValues)
print('\nMa trận S' , S.shape, ':\n', S)

## Ma trận V.T[n, n] (right-eigen vectors)
print('\nMa trận V.T', VT.shape, ':\n', VT)

## Tái tạo ma trận ban đầu
print('\nKiểm chứng lại phép phân rã:\n', np.rint(U @ S @ VT).astype(int))

Ma trận U (3, 3) :
 [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]

Ma trận S (3, 2) :
 [[9.52551809 0.        ]
 [0.         0.51430058]
 [0.         0.        ]]

Ma trận V.T (2, 2) :
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]

Kiểm chứng lại phép phân rã:
 [[1 2]
 [3 4]
 [5 6]]


In [9]:
## Áp dụng SVD với ma trận U[m, k], VT[k, n] với k = min(m, n)
A = ma_tran_hcn1
m = A.shape[0]  # rows
n = A.shape[1]  # cols
k = min(m, n)

U, sglrValues, VT = svd(A, full_matrices = False)

## Ma trận U[m, k] (left-eigen vectors)
print('Ma trận U' , U.shape, ':\n', U)

## Ma trận đường chéo S[k, k] chứa singular values
S = np.zeros(k * k).reshape((k, k))
S = np.diag(sglrValues)
print('\nMa trận S' , S.shape, ':\n', S)

## Ma trận V.T[k, n] (right-eigen vectors)
print('\nMa trận V.T', VT.shape, ':\n', VT)

## Tái tạo ma trận ban đầu
print('\nKiểm chứng lại phép phân rã:\n', np.rint(U @ S @ VT).astype(int))

Ma trận U (3, 2) :
 [[-0.2298477   0.88346102]
 [-0.52474482  0.24078249]
 [-0.81964194 -0.40189603]]

Ma trận S (2, 2) :
 [[9.52551809 0.        ]
 [0.         0.51430058]]

Ma trận V.T (2, 2) :
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]

Kiểm chứng lại phép phân rã:
 [[1 2]
 [3 4]
 [5 6]]


In [11]:
## Áp dụng Compact SVD
S     = np.diag(sglrValues)
S_inv = np.diag(1 / sglrValues)
VT    = VT[:m, :n]
U     = A @ (VT.T) @ S_inv

print('\nMa trận U' , U.shape, ':\n', U)
print('\nMa trận S' , S.shape, ':\n', S)
print('\nMa trận V.T', VT.shape, ':\n', VT)

print('\nKiểm chứng lại phép phân rã:\n', np.rint(U @ S @ VT).astype(int))


Ma trận U (3, 2) :
 [[-0.2298477   0.88346102]
 [-0.52474482  0.24078249]
 [-0.81964194 -0.40189603]]

Ma trận S (2, 2) :
 [[9.52551809 0.        ]
 [0.         0.51430058]]

Ma trận V.T (2, 2) :
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]

Kiểm chứng lại phép phân rã:
 [[1 2]
 [3 4]
 [5 6]]


---
### **Nhận xét:**
- Sự khác biệt giữa 2 phương pháp được thể hiện đối với các ma trận hình chữ nhật
---