## Câu 4. Kiểm định trung bình 2 mẫu
(1 điểm)

Hai tập tin Duong_huyet_TRUOC.txt và Duong_huyet_SAU.txt lưu trữ hai mẫu dữ liệu về chỉ số đường huyết (mg/dL) của các bệnh nhân được đo trước và sau khi sử dụng thử nghiệm một loại thuốc mới T của hãng dược phẩm D.

4.1) Đọc và xem thông tin của dữ liệu.

4.2) Với alpha = 0.05, hãy cho kết luận về giả thuyết H0: “Hai quần thể có cùng giá trị trung bình.” bằng 2 phương pháp:

a) Tính toán truyền thống, và

b) Dùng các hàm thống kê có sẵn.

In [3]:
import numpy as np
from scipy   import stats



In [52]:
# 4.1) Read and view information about the data
data_before = np.loadtxt("Data/Duong_huyet_TRUOC.txt")
data_after = np.loadtxt("Data/Duong_huyet_SAU.txt")

print("Data before:", data_before)
print("Data after:", data_after)

Data before: [[134. 130. 140. 151.]
 [143. 134. 136. 144.]
 [150. 135. 160. 141.]
 [143. 140. 138. 141.]
 [148. 146. 140. 146.]
 [151. 138. 151. 139.]
 [151. 128. 146. 147.]
 [152. 142. 144. 134.]
 [142. 146. 142. 136.]
 [122. 134. 145. 147.]]
Data after: [[130. 145. 126. 146.]
 [164. 130. 132. 152.]
 [145. 129. 133. 155.]
 [140. 127. 139. 137.]
 [131. 126. 145. 148.]
 [125. 132. 126. 126.]
 [126. 135. 131. 129.]
 [147. 136. 129. 136.]
 [156. 146. 130. 146.]
 [132. 142. 132. 132.]]


In [55]:
xem lại bài 7.4

SyntaxError: invalid syntax (1738225503.py, line 1)

In [53]:
# 4.2) Test the hypothesis H0: "Hai quần thể có cùng giá trị trung bình."
# a) Traditional calculation

mean_before = np.mean(data_before)
print(mean_before)
mean_after = np.mean(data_after)
std_before = np.std(data_before, ddof=1)
std_after = np.std(data_after, ddof=1)
n_before = len(data_before)
n_after = len(data_after)

# Calculate the t-value and p-value using the two-sample t-test formula
t_value = (mean_before - mean_after) / np.sqrt((std_before**2/n_before) + (std_after**2/n_after))
p_value = 2 * (1 - stats.t.cdf(np.abs(t_value), n_before + n_after - 2))
print(p_value)
# Compare p-value with alpha
alpha = 0.05
if p_value < alpha:
    conclusion_a = "Reject H0: The two populations have different means."
else:
    conclusion_a = "Fail to reject H0: The two populations have the same mean."

print("Traditional calculation conclusion:", conclusion_a)



141.925
0.20809883413832475
Traditional calculation conclusion: Fail to reject H0: The two populations have the same mean.


In [54]:
# b) Using available statistical functions
data_before.shape = (40,1)
data_after.shape = (40,1)
mean_before = np.mean(data_before)
print(mean_before)
# print(data_before)
t_value, p_value = stats.ttest_ind(data_before, data_after, equal_var = False)
# p_value = [0.4460874  0.42216337 0.00063854 0.60380677]
print(p_value)
# Compare p-value with alpha
if p_value[0] < alpha:
    conclusion_b = "Reject H0: The two populations have different means."
else:
    conclusion_b = "Fail to reject H0: The two populations have the same mean."

print("Using statistical functions conclusion:", conclusion_b)

141.925
[0.0109464]
Using statistical functions conclusion: Reject H0: The two populations have different means.


In [21]:
# b) Using available statistical functions
t_value, p_value = stats.ttest_ind(data_before, data_after, equal_var = False)
p_value = [0.4460874  0.42216337 0.00063854 0.60380677]

# Compare p-value with alpha
for p in p_value:
    if p < alpha:
        conclusion_b = "Reject H0: The two populations have different means."
    else:
        conclusion_b = "Fail to reject H0: The two populations have the same mean."

    print("Using statistical functions conclusion:", conclusion_b)

Using statistical functions conclusion: Fail to reject H0: The two populations have the same mean.
Using statistical functions conclusion: Fail to reject H0: The two populations have the same mean.
Using statistical functions conclusion: Reject H0: The two populations have different means.
Using statistical functions conclusion: Fail to reject H0: The two populations have the same mean.


In [37]:
# b) Using available statistical functions
t_value, p_value = stats.ttest_ind(data_before, data_after, equal_var = False)
p_values = [0.4460874, 0.42216337, 0.00063854, 0.60380677]
print(p_value)
alpha = 0.05

reject_h0 = any(p < alpha for p in p_values)

if reject_h0:
    overall_conclusion = "Reject H0: The two populations have different means."
else:
    overall_conclusion = "Fail to reject H0: The two populations have the same mean."

print("Overall conclusion:", overall_conclusion)

[0.0109464]
Overall conclusion: Reject H0: The two populations have different means.


In [24]:
data_before.shape

(10, 4)

In [31]:
data_before.shape = (40,1)

In [33]:
data_after.shape = (40,1)

In [36]:
data_before

array([[134.],
       [130.],
       [140.],
       [151.],
       [143.],
       [134.],
       [136.],
       [144.],
       [150.],
       [135.],
       [160.],
       [141.],
       [143.],
       [140.],
       [138.],
       [141.],
       [148.],
       [146.],
       [140.],
       [146.],
       [151.],
       [138.],
       [151.],
       [139.],
       [151.],
       [128.],
       [146.],
       [147.],
       [152.],
       [142.],
       [144.],
       [134.],
       [142.],
       [146.],
       [142.],
       [136.],
       [122.],
       [134.],
       [145.],
       [147.]])