# **BT thực hành 1.3: Hệ phương trình tuyến tính**


> Cập nhật: **07/2023**



In [15]:
## Thư viện
import numpy        as np
import warnings
warnings.filterwarnings('ignore')

from   numpy.linalg import det, inv, matrix_rank

---
## **Yêu cầu 1: Giải hệ PT tuyến tính: Ax = b**
- Ma trận hệ số A: [[1, -2], [0, 4]]
- Vector hệ số tự do b: [1, -2]
### $ Ax = b => x = A^{-1}.b $
---

In [16]:
## Ma trận hệ số A
A = np.array([[1, -2], [0, 4]])

## Kiểm tra tính khả nghịch của A
print(f'det(A) = {det(A)}')

det(A) = 4.0


In [17]:
## Vector hệ số tự do b
b = np.array([1, -2])
b

array([ 1, -2])

In [18]:
## Giải hệ phương trình dựa trên ma trận nghịch đảo: X = inv(A) @ b
x = inv(A) @ b
print('Hệ nghiệm (x1, x2) =', x)

Hệ nghiệm (x1, x2) = [ 0.  -0.5]


In [19]:
## Sử dụng hàm numpy.linalg.solve()
print('Hệ nghiệm (x1, x2) =', np.linalg.solve(A, b))

Hệ nghiệm (x1, x2) = [ 0.  -0.5]


---
## **Yêu cầu 2: Giải hệ PT tuyến tính**
#### 2x - 2y + z = -3
#### x + 3y - 2z = 1
#### 3x - y - z = 2
---

In [20]:
A = np.array([[2, -2, 1], [1, 3, -2], [3, -1, -1]])
b = np.array([-3, 1, 2])

## Kiểm tra tính khả nghịch của A
print(f'det(A) = {det(A)}')

det(A) = -9.999999999999998


In [21]:
## Nghiệm của hệ PT
x = inv(A) @ b
print('Hệ nghiệm (x1, x2, x3) =', x)

Hệ nghiệm (x1, x2, x3) = [-1.4 -2.  -4.2]


In [22]:
## Kiểm chứng lại nghiệm của PT : A.x = b
print('b =', A @ x)

b = [-3.  1.  2.]


---
## **Yêu cầu 3: Giải hệ PT tuyến tính (VÔ NGHIỆM)**
#### 3x + 2y = 5
#### 6x + 4y = 1
---

In [23]:
A = np.array([[3, 2], [6, 4]])
b = np.array([5, 1])

## Kiểm tra tính khả nghịch của A
print(f'det(A) = {det(A)}')  # singular matrix

det(A) = 0.0


In [24]:
## Áp dụng định lý Kronecker – Capelli
rank_A = matrix_rank(A)
print(f'Hạng của ma trận [A] = {rank_A}')

A_B = np.array([[3, 2, 5], [6, 4, 1]])
rank_AB = matrix_rank(A_B)
print(f'Hạng của dạng mở rộng [A|B] = {rank_AB}')

if (det(A) == 0):
    if (rank_AB == rank_A):
        print('Hệ phương trình VÔ ĐỊNH')
    else:
        print('Hệ phương trình VÔ NGHIỆM')

Hạng của ma trận [A] = 1
Hạng của dạng mở rộng [A|B] = 2
Hệ phương trình VÔ NGHIỆM


---
## **Yêu cầu 4: Giải hệ PT tuyến tính (VÔ ĐỊNH)**
#### 3x + 2y = 5
#### 6x + 4y = 10
---

In [25]:
A = np.array([[3, 2], [6, 4]])
b = np.array([5, 10])

## Kiểm tra tính khả nghịch của A
print(f'det(A) = {det(A)}')  # singular matrix

det(A) = 0.0


In [26]:
## Áp dụng định lý Kronecker – Capelli
rank_A = matrix_rank(A)
print(f'Hạng của ma trận [A] = {rank_A}')

A_B = np.array([[3, 2, 5], [6, 4, 10]])
rank_AB = matrix_rank(A_B)
print(f'Hạng của dạng mở rộng [A|B] = {rank_AB}')

if (det(A) == 0):
    if (rank_AB == rank_A):
        print('Hệ phương trình VÔ ĐỊNH')
    else:
        print('Hệ phương trình VÔ NGHIỆM')

Hạng của ma trận [A] = 1
Hạng của dạng mở rộng [A|B] = 1
Hệ phương trình VÔ ĐỊNH


---
## **Yêu cầu 5: Giải hệ phương trình tuyến tính**
Một nhà đầu tư có vốn 500K muốn đầu tư vào 3 cổ phiếu A, B, C. Hãy xác định số tiền cần đầu tư vào A, B, C dựa trên những điều kiện ràng buộc như sau ($Phan$  $Ngô$ $Tuấn$ $Anh$):
- Giá trị cổ phiếu A, B, C lần lượt là 50, 70, 30
- Tỷ lệ lợi nhuận (dự báo) A, B, C lần lượt là 12%, 16%, 9%
- Mua số cổ phiếu A gấp đôi số cổ phiếu B
- Mục tiêu lợi nhuận 13%/năm
---

In [27]:
## Mô hình hóa bài toán --> Xây dựng hệ phương trình tuyến tính
##    Đặt x1, x2, x3 lần lượt là số lượng cổ phiếu A, B, C cần mua

## (.12 * 50) * x1 + (.16 * 70) * x2 + (.9 * 30) * x3 = (.13 * 500000)
A = np.array([[50, 70, 30],
              [1, -2, 0],
              [(.12 * 50), (.16 * 70), (.09 * 30)]])
b = np.array([500000, 0, (.13 * 500000)])

In [28]:
## Kiểm tra tính khả nghịch của A
print(f'det(A) = {det(A)}')



det(A) = 237.00000000000009


In [29]:
inv(A)

array([[-0.02278481,  0.62025316,  0.25316456],
       [-0.01139241, -0.18987342,  0.12658228],
       [ 0.0978903 , -0.5907173 , -0.71729958]])

In [30]:
x = inv(A)@b
print(x)

[5063.29113924 2531.64556962 2320.67510549]


In [14]:
## Nghiệm của hệ PT
x = inv(A) @ b
print(f'Số lượng cổ phiếu A nên mua = {int(x[0])}')
print(f'Số lượng cổ phiếu B nên mua = {int(x[1])}')
print(f'Số lượng cổ phiếu C nên mua = {int(x[2])}')

Số lượng cổ phiếu A nên mua = 5063
Số lượng cổ phiếu B nên mua = 2531
Số lượng cổ phiếu C nên mua = 2320
