# **BT thực hành 1.4: Tìm k láng giềng gần nhất** (*k-Nearest Neighbors*)


> Cập nhật: **07/2023**



In [1]:
## Môi trường lập trình
from google.colab import drive
drive.mount("/content/gdrive", force_remount = True)
folder = '/content/gdrive/My Drive/Edu/Chia se hoc lieu/LDS3/Bai tap HV/Ch1_Linear_Algebra'

ModuleNotFoundError: No module named 'google'

In [1]:
## Thư viện
import numpy      as np
import pandas     as pd
import warnings
warnings.filterwarnings('ignore')

from numpy.linalg import norm

---
## **Yêu cầu 1:**
*   Tính các khoảng cách từ vector v (hoa mới) đến mỗi dòng (mẫu hoa) trong **iris.csv**
---


In [2]:
## Khởi tạo (tùy ý) v là hoa mới mua rất đẹp, nhưng không biết là loại hoa gì !
##    Phương pháp: tìm những mẫu hoa có các đặc tính gần giống với hoa mới mua nhất
v = np.array([5.2, 3.2, 1.3, 0.1])

In [3]:
## Đọc tập tin iris.csv vào dataframe và tạo ma trận A
df = pd.read_csv('Data/iris.csv')
A  = np.array(df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']])
print(A)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [5]:
## Tính khoảng cách (Euclidean) từ v_new đến mỗi dòng của ma trận A (150 mẫu đã thu thập)
A_v       = (A - v) # chuyển từ khái niệm NORM của vector sang KHOẢNG CÁCH giữa 2 điểm
distances = []
for i in range(A_v.shape[0]):
    distances.append(norm(A_v[i, :])) # L2 norm
result = np.array(distances)

result[:5]

array([0.34641016, 0.38729833, 0.50990195, 0.64807407, 0.46904158])

In [5]:
A_v       = (A - v)
A_v

array([[-0.1,  0.3,  0.1,  0.1],
       [-0.3, -0.2,  0.1,  0.1],
       [-0.5,  0. ,  0. ,  0.1],
       [-0.6, -0.1,  0.2,  0.1],
       [-0.2,  0.4,  0.1,  0.1],
       [ 0.2,  0.7,  0.4,  0.3],
       [-0.6,  0.2,  0.1,  0.2],
       [-0.2,  0.2,  0.2,  0.1],
       [-0.8, -0.3,  0.1,  0.1],
       [-0.3, -0.1,  0.2,  0. ],
       [ 0.2,  0.5,  0.2,  0.1],
       [-0.4,  0.2,  0.3,  0.1],
       [-0.4, -0.2,  0.1,  0. ],
       [-0.9, -0.2, -0.2,  0. ],
       [ 0.6,  0.8, -0.1,  0.1],
       [ 0.5,  1.2,  0.2,  0.3],
       [ 0.2,  0.7,  0. ,  0.3],
       [-0.1,  0.3,  0.1,  0.2],
       [ 0.5,  0.6,  0.4,  0.2],
       [-0.1,  0.6,  0.2,  0.2],
       [ 0.2,  0.2,  0.4,  0.1],
       [-0.1,  0.5,  0.2,  0.3],
       [-0.6,  0.4, -0.3,  0.1],
       [-0.1,  0.1,  0.4,  0.4],
       [-0.4,  0.2,  0.6,  0.1],
       [-0.2, -0.2,  0.3,  0.1],
       [-0.2,  0.2,  0.3,  0.3],
       [ 0. ,  0.3,  0.2,  0.1],
       [ 0. ,  0.2,  0.1,  0.1],
       [-0.5,  0. ,  0.3,  0.1],
       [-0

---
## **Yêu cầu 2:**
- Viết hàm Distance(A, v) để tính khoảng cách từ vector v đến ma trận A
- Hàm trả về vector là các khoảng cách (tính theo norm 2)
---

In [6]:
def Distance(A, v):
    A_v       = (A - v)
    distances = []
    for i in range(A_v.shape[0]):
        distances.append(norm(A_v[i, :]))
    return np.array(distances)

In [7]:
result = Distance(A, v)
result[:5]

array([0.34641016, 0.38729833, 0.50990195, 0.64807407, 0.46904158])

---
## **Yêu cầu 3: Viết hàm KNN(A, v, k = 3) để tìm k phần tử gần nhất (ngầm định 3)**
- B1: Gọi đến hàm Distance để tính khoảng cách từ vector v đến ma trận A
- B2: Tạo ma trận D có 2 cột: D[index (bắt đầu từ 0), distance]
- B3: Sắp xếp D tăng dần theo khoảng cách và chọn ra k phần tử có khoảng cách nhỏ nhất

##### ==> Hàm trả về 2 arrays: $index$ và $distance$
---

In [8]:
## Hàm tìm k láng giềng gần nhất với v (ngầm định k = 3)
def KNN(A, v, k = 3):
    # Khoảng cách từ v đến ma trận A
    distances = Distance(A, v)

    # Tạo 2 arrays: index và distance
    D1 = np.arange(distances.shape[0]) # index
    D  = np.c_[D1, distances] # Ghép nối theo CỘT để tạo ma trận có 2 cột (numpy.r_ : ghép nối theo DÒNG)
    D  = D[np.argsort(D[:, 1])][:k] # sắp xếp tăng dần theo distance và chọn k phần tử có distance nhỏ nhất
    return (D[:,0], D[:,1]) # trả về 2 array: index, distance

In [89]:
## Hàm tìm k láng giềng gần nhất với v (ngầm định k = 3)
def KNN3(A, v, k = 3):
    # Khoảng cách từ v đến ma trận A
    distances = Distance(A, v)

    # Tạo 2 arrays: index và distance
    # D1 = np.arange(distances.shape[0]) # index
    # D  = np.c_[D1, distances] # Ghép nối theo CỘT để tạo ma trận có 2 cột (numpy.r_ : ghép nối theo DÒNG)
    id3  = np.argsort(distances)[:k] # sắp xếp tăng dần theo distance và chọn k phần tử có distance nhỏ nhất
    return id3 , distances[id3] # trả về 2 array: index, 

In [90]:
id3, dis = KNN3(A,v,10)

In [86]:
id3

array([28, 35, 49, 39,  0,  7, 27, 34,  9, 37])

In [ ]:
distances

In [83]:
df.iloc[id3]

sepal_length  sepal_width  petal_length  petal_width species
28           5.2          3.4           1.4          0.2  setosa
35           5.0          3.2           1.2          0.2  setosa
49           5.0          3.3           1.4          0.2  setosa
39           5.1          3.4           1.5          0.2  setosa
0            5.1          3.5           1.4          0.2  setosa
7            5.0          3.4           1.5          0.2  setosa
27           5.2          3.5           1.5          0.2  setosa
34           4.9          3.1           1.5          0.1  setosa
9            4.9          3.1           1.5          0.1  setosa
37           4.9          3.1           1.5          0.1  setosa

In [63]:
## Hàm tìm k láng giềng gần nhất với v (ngầm định k = 3)
def KNN2(A, v, k = 3):
    # Khoảng cách từ v đến ma trận A
    distances = Distance(A, v)
    D1 = pd.DataFrame(distances, index = np.arange(distances.shape[0]),columns =['distance'])
    D1 = D1.sort_values(by=['distance'], ascending = True)[:k]
    D1 = D1.reset_index()
    return D1

In [76]:
distances2 = Distance(A, v)
index = np.arange(distances2.shape[0]) # index
D2  = np.c_[index, distances2] 

In [78]:
D3  = np.argsort(D2[:, 1])
D3

array([ 28,  35,  49,  39,   0,   7,  27,  34,   9,  37,   1,  17,  40,
        25,  36,  31,  12,   4,  20,  45,   2,  26,  30,  11,  48,  23,
        10,  29,  47,  21,   3,  19,   6,  46,  43,  24,  16,  22,  42,
        38,   8,   5,  18,  44,  32,  13,  14,  33,  41,  15,  98,  57,
        93,  79,  64,  60,  81,  80,  69,  82,  59,  92,  67,  89,  88,
        53,  99,  71,  62,  95,  96,  94,  61,  90,  97,  74,  55,  84,
        66,  78,  87,  85,  75, 106,  91,  65,  51,  73,  63,  68,  58,
        54,  56,  70,  86, 138, 126,  50,  72,  76, 127, 121, 119, 123,
        83, 133,  52, 149, 113, 101, 142,  77, 146, 110, 114, 147, 111,
       134, 137, 141, 116, 115, 145, 103, 148, 139, 128, 112, 132, 136,
       124, 108, 140, 104, 129, 120, 144, 143, 102, 125, 100, 130, 107,
       109, 135, 131, 105, 122, 117, 118])

In [79]:
D2[:, 1]

array([0.34641016, 0.38729833, 0.50990195, 0.64807407, 0.46904158,
       0.88317609, 0.67082039, 0.36055513, 0.8660254 , 0.37416574,
       0.58309519, 0.54772256, 0.45825757, 0.94339811, 1.00995049,
       1.34907376, 0.78740079, 0.38729833, 0.9       , 0.67082039,
       0.5       , 0.6244998 , 0.78740079, 0.58309519, 0.75498344,
       0.42426407, 0.50990195, 0.37416574, 0.24494897, 0.59160798,
       0.51961524, 0.45825757, 0.92195445, 1.05356538, 0.37416574,
       0.24494897, 0.43588989, 0.37416574, 0.83066239, 0.31622777,
       0.41231056, 1.15758369, 0.80622577, 0.68556546, 0.90553851,
       0.5       , 0.68556546, 0.6164414 , 0.55677644, 0.26457513,
       4.0607881 , 3.69323706, 4.22137418, 3.10322413, 3.8340579 ,
       3.47706773, 3.87685439, 2.35372046, 3.79209705, 2.94957624,
       2.67020598, 3.3015148 , 3.12089731, 3.76164857, 2.64196896,
       3.68239053, 3.52136337, 3.04302481, 3.76828874, 2.9       ,
       3.95347948, 3.1144823 , 4.07676342, 3.7067506 , 3.45976

In [74]:
id2 = np.array(150)

In [75]:
id2

array(150)

In [64]:
D1 = KNN2(A,v,10)

In [40]:
D1

val
28  0.244949
35  0.244949
49  0.264575
39  0.316228
0   0.346410
7   0.360555
27  0.374166
34  0.374166
9   0.374166
37  0.374166

In [65]:
idx = D1.iloc[0:]

In [69]:
idx_arr = np.array(idx['index'], dtype = np.integer)

In [70]:
idx_arr

array([28, 35, 49, 39,  0,  7, 27, 34,  9, 37])

In [71]:
df.iloc[idx_arr]

sepal_length  sepal_width  petal_length  petal_width species
28           5.2          3.4           1.4          0.2  setosa
35           5.0          3.2           1.2          0.2  setosa
49           5.0          3.3           1.4          0.2  setosa
39           5.1          3.4           1.5          0.2  setosa
0            5.1          3.5           1.4          0.2  setosa
7            5.0          3.4           1.5          0.2  setosa
27           5.2          3.5           1.5          0.2  setosa
34           4.9          3.1           1.5          0.1  setosa
9            4.9          3.1           1.5          0.1  setosa
37           4.9          3.1           1.5          0.1  setosa

---
## **Yêu cầu 4:**
- Tìm k phần tử gần vector v nhất
- In ra index và distance
- In ra df.iloc[ind] và cho nhận xét
---

In [9]:
## Tìm k láng giềng gần nhất
k        = 9 # chọn tùy ý
idx, dist = KNN(A, v, k)

In [10]:
## Index của các láng giềng gần vector v nhất
idx.astype(int)

array([28, 35, 49, 39,  0,  7, 34, 27,  9])

In [11]:
## Khoảng cách tương ứng giữa v và các láng giềng gần nhất
dist

array([0.24494897, 0.24494897, 0.26457513, 0.31622777, 0.34641016,
       0.36055513, 0.37416574, 0.37416574, 0.37416574])

In [12]:
## Xem dữ liệu của k láng giềng gần nhất
df.iloc[idx]

sepal_length  sepal_width  petal_length  petal_width species
28           5.2          3.4           1.4          0.2  setosa
35           5.0          3.2           1.2          0.2  setosa
49           5.0          3.3           1.4          0.2  setosa
39           5.1          3.4           1.5          0.2  setosa
0            5.1          3.5           1.4          0.2  setosa
7            5.0          3.4           1.5          0.2  setosa
34           4.9          3.1           1.5          0.1  setosa
27           5.2          3.5           1.5          0.2  setosa
9            4.9          3.1           1.5          0.1  setosa

In [ ]:
## Nhận xét: với v = [5.2, 3.2, 1.3, 0.1] thì các láng giềng gần nhất thuộc nhóm hoa setosa

In [13]:
## Nếu chọn 3 láng giềng gần nhất (giá trị ngầm định): không cần gởi tham số k
idx, dist = KNN(A, v)
df.iloc[idx]

sepal_length  sepal_width  petal_length  petal_width species
28           5.2          3.4           1.4          0.2  setosa
35           5.0          3.2           1.2          0.2  setosa
49           5.0          3.3           1.4          0.2  setosa